### ISSUE TITLE
in math_utils.py function MAPE "return np.mean(np.abs(v_ - v) / (v + 1e-5))" should be "return np.mean(np.abs(v_ - v) / (v_ + 1e-5))"?

### ISSUE THREAD

**Issue by xyk0058** [PKUAI26/STGCN-IJCAI-18#3]
in math_utils.py function MAPE "return np.mean(np.abs(v_ - v) / (v + 1e-5))" should be "return np.mean(np.abs(v_ - v) / (v_ + 1e-5))"?

**Comment by VeritasYin** [comment]
Hi,
'v_' stands for the prediction while 'v' denotes the ground truth. As for the definition of this metric, please refer to [MAPE](https://en.wikipedia.org/wiki/Mean_absolute_percentage_error).
Thank you

**Comment by xyk0058** [comment]
thanks. I also have another question. First time I run your code with PeMS(more than 2000 nodes), the MAPE nearly 4000%. I think there is something wrong with v_ and v.
Now I think maybe 1e-5 effect this result if v_=0.
Should I keep these data with v_=0?
