### ISSUE TITLE
question about mape

### ISSUE THREAD

**Issue by xyk0058** [PKUAI26/STGCN-IJCAI-18#4]
thanks. I also have another question. First time I run your code with PeMS(more than 2000 nodes), the MAPE nearly 4000%. I think there is something wrong with v_ and v.
Now I think maybe 1e-5 effect this result if v_=0.
Should I keep these data with v_=0?

I found in DCRNN. They use masked_mape_np to solve this problem.
def masked_mape_np(preds, labels, null_val=np.nan):
    with np.errstate(divide='ignore', invalid='ignore'):
        if np.isnan(null_val):
            mask = ~np.isnan(labels)
        else:
            mask = np.not_equal(labels, null_val)
        mask = mask.astype('float32')
        mask /= np.mean(mask)
        mape = np.abs(np.divide(np.subtract(preds, labels).astype('float32'), labels))
        mape = np.nan_to_num(mask * mape)
        return np.mean(mape)

Which I should use to reproduce the result in paper? 
Thanks again!

**Comment by VeritasYin** [comment]
Hi,
As we described in our paper, we preprocessed the dataset by the linear interpolation to avoid such abnormal situation. You can also use the mask to calculate this metric.
Thank you

**Comment by xyk0058** [comment]
I was confused about if you preprocessed the dataset by the linear interpolation, why you plus 1e-5 in fomula.

**Comment by VeritasYin** [comment]
You can regard this as safety precaution.

**Comment by xyk0058** [comment]
Thanks!
