### ISSUE TITLE
Best performing hyperparameters

### ISSUE THREAD

**Issue by kyungeuuun** [PKUAI26/STGCN-IJCAI-18#5]
I wonder about the best hyperparameter setting, 
for specific, the number of channels in ST-Conv blocks.
According to your paper, 
the channels of three layers in ST-Conv block are 64, 16, 64 respectively.
Does this mean two blocks have the same setup?

**Comment by VeritasYin** [comment]
Hi,
As we described in the paper, the channels of three layers in ST-Conv block are 64, 16, 64 respectively. For the first block, the channel of input is '1'. The rest remain the same settings.
Thank you

**Comment by kyungeuuun** [comment]
Thanks! :)
