### ISSUE TITLE
base_line ARIMA

### ISSUE THREAD

**Issue by ZGX010** [PKUAI26/STGCN-IJCAI-18#7]
你好　ＡＲＩＭＡ模型您是用什么实现的？另外ＡＲＩＭＡ应该是只能通过t时刻之前预测t时刻，那么t+3时刻怎么预测

**Comment by VeritasYin** [comment]
Hi 文章中的ARIMA模型是通过[statsmodels.tsa.arima_model.ARIMA](http://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.html)构建的，我们针对每一条路选取了最佳的（p,d,q）参数。模型可以通过滚动的方式逐步迭代预测，即t_his -> \hat{t}, t_his, \hat{t} -> \hat{t+1}, etc. 也可以一次性给出n个预测结果。

**Comment by ZGX010** [comment]
大佬，ＡＲＩＭＡ的代码方便膜拜一下不？跪求！
